import Multi.term2
#print axioms T.NF_is_wellfounded
#print axioms T.dom_eq_zero
#print axioms T.dom_omega_index_one
#print axioms T.add_P
#print axioms T.mul_principal_cases
#print axioms T.mul_lt_P
#print axioms T.iter_lt
#print axioms T.fund_lt_of_domain
#print axioms T.first_le_of_head_le
#print axioms T.le_of_not_lt
#print axioms T.dom_omega_index_bound
#print axioms T.dom_ne_omega_below_omega_one
#print axioms T.fund_lt_below_omega_one
#print axioms T.head_mono
#print axioms T.isNF_replace_tail
#print axioms T.dom_one_cases
#print axioms T.fund_one_properties
#print axioms T.fund_one_isNF
#print axioms T.fund_one_regular
#print axioms T.mul_principal_add
#print axioms T.mul_principal_head_le
#print axioms T.mul_principal_isNF
#print axioms T.fund_principal_successor_isNF
#print axioms T.lt_principal_of_head_lt
#print axioms T.mul_principal_ofNat_succ
#print axioms T.mul_principal_cofinal
#print axioms T.fund_principal_successor_cofinal
#print axioms T.GBound_zero
#print axioms T.GBound_P
#print axioms T.dom_omega_index_lt
#print axioms T.dom_omega_index_isNF
#print axioms T.GBound_dom_index
#print axioms T.GBound_mul_principal
#print axioms T.GBound_fund_one
#print axioms T.GBound_fund
#print axioms T.ofNat_lt_index
#print axioms T.ofNat_in_domain
#print axioms T.fund_ofNat_lt
#print axioms T.mem_G_ofNat
#print axioms T.GBound_fund_ofNat
#print axioms T.fund_nonzero_tail_isNF
#print axioms T.fund_nonzero_tail_cofinal
#print axioms T.OT_characterization_of_fundamental_properties
