import Multi.term3
#print axioms T
#print axioms T.lt
#print axioms lt_Z_Z_inv
#print axioms lt_P_Z_inv
#print axioms lt_Z_inv
#print axioms lt_inv
#print axioms T.decLt
#print axioms T.lt_irrefl
#print axioms T.lt_trans
#print axioms T.lt_asymm
#print axioms T.lt_total
#print axioms T.Z_le
#print axioms T.add
#print axioms T.mul
#print axioms T.iter
#print axioms T.size
#print axioms T.size_P
#print axioms T.size_lt_size_P_first
#print axioms T.size_lt_size_P_second
#print axioms T.size_lt_size_P_third
#print axioms T.size_lt_size_P_fourth
#print axioms Dom
#print axioms T.dom
#print axioms T.dom_omega_size
#print axioms Dom.cases_eq
#print axioms T.fund
